# Generated by Django 2.1.8 on 2019-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(db_index=True, default=1, max_length=64, verbose_name='openid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
    ]
